### ISSUE TITLE
Root password update 'password' column does not exist

### ISSUE THREAD

**Issue by huyby** [mjanser/ansible-role-mysql#3]
Hi,

I bumped into an issue when applying the role on a Ubuntu Xenial 16.10 AMI on AWS. It seems that the 'password' column in MySQL 5.7 has changed to 'authentication_string'. The column is hardcoded in the "root_auth_plugin.yml" play. Solution could be a variable with a default filter to 'password'; or a default variable with 'password' value that can be overriden; and/or a detection of the installed MySQL version and auto-change the variable to 'authentication_string' when version is >= 5.7?

**Comment by mjanser** [comment]
I updated the change of the auth plugin and released a new version. Can you check if it now works for you?
